/********************************************************************************
** Form generated from reading UI file 'customerclient.ui'
**
** Created by: Qt User Interface Compiler version 6.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CUSTOMERCLIENT_H
#define UI_CUSTOMERCLIENT_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CustomerClient
{
public:
    QStackedWidget *stackedWidget;
    QWidget *page;
    QPushButton *Btn_first;
    QWidget *page_2;
    QLabel *lb_Logo;
    QLineEdit *ID_Edit;
    QLineEdit *PW_Edit;
    QLabel *lb_ID;
    QLabel *lb_Pw;
    QPushButton *Btn_Login;
    QPushButton *Btn_Join;
    QPushButton *Btn_FindID;
    QPushButton *Btn_FindPW;
    QWidget *page_3;
    QLabel *lb_JoinLogo;
    QLabel *lb_Join_ID;
    QLabel *lb_Join_PW;
    QLineEdit *ID_JoinEdit;
    QLineEdit *PW_JoinEdit;
    QLabel *lb_Join_NAME;
    QLineEdit *NAME_JoinEdit;
    QLabel *lb_Join_PHONE;
    QLineEdit *PHONE_JoinEdit;
    QLabel *lb_Join_NICKNAME;
    QLineEdit *NICKNAME_JoinEdit;
    QPushButton *Btn_confirmID;
    QPushButton *Btn_confirmPHONE;
    QPushButton *Btn_confirmNICKNAME;
    QPushButton *Btn_confirmJoin;
    QPushButton *Btn_JoinBack;
    QWidget *page_4;
    QPushButton *Btn_confirmFindID;
    QLineEdit *NAME_FindIDEdit;
    QPushButton *Btn_FindIDBack;
    QLineEdit *NICKNAME_FindIDEdit;
    QLabel *lb_FindID_NAME;
    QLabel *lb_FindIDLogo;
    QLabel *lb_FindID_NICKNAME;
    QWidget *page_5;
    QLabel *lb_FindPWLogo;
    QPushButton *Btn_FindPWBack;
    QLabel *lb_FindPW_NAME;
    QLineEdit *ID_FindPWEdit;
    QLabel *lb_FindPW_ID;
    QPushButton *Btn_confirmFindPW;
    QLineEdit *NICKNAME_FindPWEdit;
    QLabel *lb_FindPW_NICKNAME;
    QLineEdit *NAME_FindPWEdit;
    QWidget *page_6;
    QLabel *lb_Address;
    QPushButton *Btn_Alarm;
    QPushButton *Btn_Bascket;
    QLineEdit *Search_Edit;
    QPushButton *Btn_Pizza;
    QPushButton *Btn_Chicken;
    QPushButton *Btn_Burger;
    QPushButton *Btn_Meat;
    QPushButton *Btn_Marcket1;
    QPushButton *Btn_Marcket2;
    QPushButton *Btn_Heart;
    QPushButton *Btn_Profile;
    QPushButton *Btn_Inquire;
    QPushButton *Btn_List;
    QLabel *lb_Photo_Marcket1;
    QLabel *lb_Photo_Marcket2;
    QLabel *lb_Marcket_Info2;
    QLabel *lb_Marcket_Info1;
    QLabel *label;
    QWidget *page_8;
    QPushButton *Btn_Marcket_Back;
    QLabel *lb_Image_Logo;
    QPushButton *Btn_Marcket_home;
    QPushButton *Btn_Marcket_Bascket;
    QLabel *lb_Categoryname;
    QPushButton *Btn_Marcket_choice1;
    QPushButton *Btn_Marcket_choice2;
    QPushButton *Btn_Marcket_choice3;
    QPushButton *Btn_Marcket_choice4;
    QPushButton *Btn_Marcket_choice5;
    QLabel *lb_Marcket_photo1;
    QLabel *lb_Marcket_photo2;
    QLabel *lb_Marcket_photo3;
    QLabel *lb_Marcket_photo4;
    QLabel *lb_Marcket_photo5;
    QLabel *lb_Marcket_name1;
    QLabel *lb_Marcket_name2;
    QLabel *lb_Marcket_name3;
    QLabel *lb_Marcket_name4;
    QLabel *lb_Marcket_name5;
    QLabel *lb_Detail4;
    QLabel *lb_Detail3;
    QLabel *lb_Detail5;
    QLabel *lb_Detail2;
    QLabel *lb_Detail1;
    QWidget *page_7;
    QLabel *lb_Menu_name3;
    QLabel *lb_Menu_Photo1;
    QLabel *lb_Menu_Photo3;
    QPushButton *Btn_Menu_Bascket;
    QLabel *lb_Menu_name2;
    QPushButton *Btn_Menu3;
    QLabel *lb_Menu_Photo4;
    QLabel *lb_Menu_Photo2;
    QLabel *lb_Menu_name4;
    QPushButton *Btn_Menu_home;
    QPushButton *Btn_Menu2;
    QLabel *lb_Menu_Detail2;
    QLabel *lb_Menu_Detail1;
    QLabel *lb_Menu_Detail3;
    QPushButton *Btn_Menu1;
    QPushButton *Btn_Menu4;
    QLabel *lb_Menu_name1;
    QPushButton *Btn_Menu_Back;
    QLabel *lb_Menu_Detail4;
    QLabel *lb_Menu_Photo;
    QLabel *lb_Menu_Detail;
    QLabel *lb_Menu_Price1;
    QLabel *lb_Menu_Price4;
    QLabel *lb_Menu_Price3;
    QLabel *lb_Menu_Price2;
    QWidget *page_9;
    QPushButton *Btn_Detailmenu_Bascket;
    QPushButton *Btn_Detailmenu_Back;
    QLabel *lb_Detailmenu_Photo;
    QLabel *lb_Detailmenu_Detail;
    QPushButton *Btn_Detailmenu_Home;
    QListWidget *Option_List;
    QWidget *page_10;
    QPushButton *Btn_ConfirmMenu_Home;
    QPushButton *Btn_ConfirmMenu_Back;
    QPushButton *Btn_Delivery;
    QLabel *lb_Confirm_Price;
    QPushButton *Btn_Plus_Menu;
    QListWidget *Detail_List;
    QLabel *lb_Confirm_marcketname;
    QLabel *lb_Confirm_time;
    QWidget *page_11;
    QLabel *lb_payment_name;
    QPushButton *Btn_Payment_Back;
    QPushButton *Btn_Payment;
    QListWidget *Payment_List;
    QPushButton *Btn_Payment_Home;
    QLabel *lb_Payment_Price;
    QLabel *lb_payment_time;
    QWidget *page_12;
    QLabel *lb_Result_name;
    QPushButton *Btn_Result_home;
    QListWidget *Result_List;
    QLabel *lb_Result_time;
    QWidget *page_13;
    QPushButton *Btn_Chat_Back;
    QPushButton *Btn_Chat_Home;
    QTextEdit *Chat_TextEdit;
    QLineEdit *Chat_LineEdit;
    QPushButton *Btn_Chat;

    void setupUi(QWidget *CustomerClient)
    {
        if (CustomerClient->objectName().isEmpty())
            CustomerClient->setObjectName("CustomerClient");
        CustomerClient->resize(390, 688);
        stackedWidget = new QStackedWidget(CustomerClient);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(10, 10, 375, 665));
        page = new QWidget();
        page->setObjectName("page");
        Btn_first = new QPushButton(page);
        Btn_first->setObjectName("Btn_first");
        Btn_first->setGeometry(QRect(0, 0, 375, 665));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Image/first.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_first->setIcon(icon);
        Btn_first->setIconSize(QSize(375, 665));
        Btn_first->setFlat(true);
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        lb_Logo = new QLabel(page_2);
        lb_Logo->setObjectName("lb_Logo");
        lb_Logo->setGeometry(QRect(40, 40, 300, 110));
        lb_Logo->setStyleSheet(QString::fromUtf8("\n"
"border-image: url(:/Image/Join.png);"));
        lb_Logo->setAlignment(Qt::AlignCenter);
        ID_Edit = new QLineEdit(page_2);
        ID_Edit->setObjectName("ID_Edit");
        ID_Edit->setGeometry(QRect(130, 190, 190, 40));
        PW_Edit = new QLineEdit(page_2);
        PW_Edit->setObjectName("PW_Edit");
        PW_Edit->setGeometry(QRect(130, 250, 190, 40));
        lb_ID = new QLabel(page_2);
        lb_ID->setObjectName("lb_ID");
        lb_ID->setGeometry(QRect(60, 190, 70, 40));
        QFont font;
        font.setPointSize(11);
        font.setBold(true);
        lb_ID->setFont(font);
        lb_Pw = new QLabel(page_2);
        lb_Pw->setObjectName("lb_Pw");
        lb_Pw->setGeometry(QRect(60, 250, 70, 40));
        lb_Pw->setFont(font);
        Btn_Login = new QPushButton(page_2);
        Btn_Login->setObjectName("Btn_Login");
        Btn_Login->setGeometry(QRect(60, 350, 260, 40));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Image/Login.PNG"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Login->setIcon(icon1);
        Btn_Login->setIconSize(QSize(260, 50));
        Btn_Login->setFlat(true);
        Btn_Join = new QPushButton(page_2);
        Btn_Join->setObjectName("Btn_Join");
        Btn_Join->setGeometry(QRect(60, 410, 260, 40));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Image/Join_.PNG"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Join->setIcon(icon2);
        Btn_Join->setIconSize(QSize(260, 50));
        Btn_Join->setFlat(true);
        Btn_FindID = new QPushButton(page_2);
        Btn_FindID->setObjectName("Btn_FindID");
        Btn_FindID->setGeometry(QRect(60, 470, 125, 40));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/Image/Find_ID.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_FindID->setIcon(icon3);
        Btn_FindID->setIconSize(QSize(150, 50));
        Btn_FindID->setFlat(true);
        Btn_FindPW = new QPushButton(page_2);
        Btn_FindPW->setObjectName("Btn_FindPW");
        Btn_FindPW->setGeometry(QRect(195, 470, 125, 40));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/Image/Find_PW.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_FindPW->setIcon(icon4);
        Btn_FindPW->setIconSize(QSize(150, 50));
        Btn_FindPW->setFlat(true);
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        lb_JoinLogo = new QLabel(page_3);
        lb_JoinLogo->setObjectName("lb_JoinLogo");
        lb_JoinLogo->setGeometry(QRect(40, 15, 300, 110));
        lb_JoinLogo->setStyleSheet(QString::fromUtf8("\n"
"border-image: url(:/Image/Join.png);"));
        lb_JoinLogo->setAlignment(Qt::AlignCenter);
        lb_Join_ID = new QLabel(page_3);
        lb_Join_ID->setObjectName("lb_Join_ID");
        lb_Join_ID->setGeometry(QRect(30, 130, 70, 40));
        lb_Join_ID->setFont(font);
        lb_Join_PW = new QLabel(page_3);
        lb_Join_PW->setObjectName("lb_Join_PW");
        lb_Join_PW->setGeometry(QRect(30, 190, 70, 40));
        lb_Join_PW->setFont(font);
        ID_JoinEdit = new QLineEdit(page_3);
        ID_JoinEdit->setObjectName("ID_JoinEdit");
        ID_JoinEdit->setGeometry(QRect(100, 130, 190, 40));
        PW_JoinEdit = new QLineEdit(page_3);
        PW_JoinEdit->setObjectName("PW_JoinEdit");
        PW_JoinEdit->setGeometry(QRect(100, 190, 190, 40));
        lb_Join_NAME = new QLabel(page_3);
        lb_Join_NAME->setObjectName("lb_Join_NAME");
        lb_Join_NAME->setGeometry(QRect(30, 250, 70, 40));
        lb_Join_NAME->setFont(font);
        NAME_JoinEdit = new QLineEdit(page_3);
        NAME_JoinEdit->setObjectName("NAME_JoinEdit");
        NAME_JoinEdit->setGeometry(QRect(100, 250, 190, 40));
        lb_Join_PHONE = new QLabel(page_3);
        lb_Join_PHONE->setObjectName("lb_Join_PHONE");
        lb_Join_PHONE->setGeometry(QRect(30, 310, 70, 40));
        lb_Join_PHONE->setFont(font);
        PHONE_JoinEdit = new QLineEdit(page_3);
        PHONE_JoinEdit->setObjectName("PHONE_JoinEdit");
        PHONE_JoinEdit->setGeometry(QRect(100, 310, 190, 40));
        lb_Join_NICKNAME = new QLabel(page_3);
        lb_Join_NICKNAME->setObjectName("lb_Join_NICKNAME");
        lb_Join_NICKNAME->setGeometry(QRect(30, 370, 70, 40));
        lb_Join_NICKNAME->setFont(font);
        NICKNAME_JoinEdit = new QLineEdit(page_3);
        NICKNAME_JoinEdit->setObjectName("NICKNAME_JoinEdit");
        NICKNAME_JoinEdit->setGeometry(QRect(100, 370, 190, 40));
        Btn_confirmID = new QPushButton(page_3);
        Btn_confirmID->setObjectName("Btn_confirmID");
        Btn_confirmID->setGeometry(QRect(300, 130, 60, 40));
        Btn_confirmPHONE = new QPushButton(page_3);
        Btn_confirmPHONE->setObjectName("Btn_confirmPHONE");
        Btn_confirmPHONE->setGeometry(QRect(300, 310, 60, 40));
        Btn_confirmNICKNAME = new QPushButton(page_3);
        Btn_confirmNICKNAME->setObjectName("Btn_confirmNICKNAME");
        Btn_confirmNICKNAME->setGeometry(QRect(300, 370, 60, 40));
        Btn_confirmJoin = new QPushButton(page_3);
        Btn_confirmJoin->setObjectName("Btn_confirmJoin");
        Btn_confirmJoin->setGeometry(QRect(100, 480, 260, 40));
        Btn_confirmJoin->setStyleSheet(QString::fromUtf8(""));
        Btn_confirmJoin->setIcon(icon2);
        Btn_confirmJoin->setIconSize(QSize(260, 50));
        Btn_confirmJoin->setFlat(true);
        Btn_JoinBack = new QPushButton(page_3);
        Btn_JoinBack->setObjectName("Btn_JoinBack");
        Btn_JoinBack->setGeometry(QRect(20, 480, 60, 40));
        Btn_JoinBack->setStyleSheet(QString::fromUtf8(""));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/Image/Back.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_JoinBack->setIcon(icon5);
        Btn_JoinBack->setIconSize(QSize(200, 50));
        Btn_JoinBack->setFlat(true);
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        Btn_confirmFindID = new QPushButton(page_4);
        Btn_confirmFindID->setObjectName("Btn_confirmFindID");
        Btn_confirmFindID->setGeometry(QRect(100, 480, 260, 40));
        Btn_confirmFindID->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 193, 188);\n"
"border-radius:10px;\n"
""));
        NAME_FindIDEdit = new QLineEdit(page_4);
        NAME_FindIDEdit->setObjectName("NAME_FindIDEdit");
        NAME_FindIDEdit->setGeometry(QRect(120, 190, 190, 40));
        Btn_FindIDBack = new QPushButton(page_4);
        Btn_FindIDBack->setObjectName("Btn_FindIDBack");
        Btn_FindIDBack->setGeometry(QRect(20, 480, 60, 40));
        Btn_FindIDBack->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(42, 193, 188);\n"
"border-radius:10px;\n"
""));
        NICKNAME_FindIDEdit = new QLineEdit(page_4);
        NICKNAME_FindIDEdit->setObjectName("NICKNAME_FindIDEdit");
        NICKNAME_FindIDEdit->setGeometry(QRect(120, 250, 190, 40));
        lb_FindID_NAME = new QLabel(page_4);
        lb_FindID_NAME->setObjectName("lb_FindID_NAME");
        lb_FindID_NAME->setGeometry(QRect(50, 190, 70, 40));
        lb_FindID_NAME->setFont(font);
        lb_FindIDLogo = new QLabel(page_4);
        lb_FindIDLogo->setObjectName("lb_FindIDLogo");
        lb_FindIDLogo->setGeometry(QRect(40, 40, 300, 110));
        lb_FindIDLogo->setStyleSheet(QString::fromUtf8("\n"
"border-image: url(:/Image/Join.png);"));
        lb_FindIDLogo->setAlignment(Qt::AlignCenter);
        lb_FindID_NICKNAME = new QLabel(page_4);
        lb_FindID_NICKNAME->setObjectName("lb_FindID_NICKNAME");
        lb_FindID_NICKNAME->setGeometry(QRect(50, 250, 70, 40));
        lb_FindID_NICKNAME->setFont(font);
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName("page_5");
        lb_FindPWLogo = new QLabel(page_5);
        lb_FindPWLogo->setObjectName("lb_FindPWLogo");
        lb_FindPWLogo->setGeometry(QRect(40, 40, 300, 110));
        lb_FindPWLogo->setStyleSheet(QString::fromUtf8("\n"
"border-image: url(:/Image/Join.png);"));
        lb_FindPWLogo->setAlignment(Qt::AlignCenter);
        Btn_FindPWBack = new QPushButton(page_5);
        Btn_FindPWBack->setObjectName("Btn_FindPWBack");
        Btn_FindPWBack->setGeometry(QRect(20, 480, 60, 40));
        lb_FindPW_NAME = new QLabel(page_5);
        lb_FindPW_NAME->setObjectName("lb_FindPW_NAME");
        lb_FindPW_NAME->setGeometry(QRect(50, 250, 70, 40));
        lb_FindPW_NAME->setFont(font);
        ID_FindPWEdit = new QLineEdit(page_5);
        ID_FindPWEdit->setObjectName("ID_FindPWEdit");
        ID_FindPWEdit->setGeometry(QRect(120, 190, 190, 40));
        lb_FindPW_ID = new QLabel(page_5);
        lb_FindPW_ID->setObjectName("lb_FindPW_ID");
        lb_FindPW_ID->setGeometry(QRect(50, 190, 70, 40));
        lb_FindPW_ID->setFont(font);
        Btn_confirmFindPW = new QPushButton(page_5);
        Btn_confirmFindPW->setObjectName("Btn_confirmFindPW");
        Btn_confirmFindPW->setGeometry(QRect(100, 480, 260, 40));
        NICKNAME_FindPWEdit = new QLineEdit(page_5);
        NICKNAME_FindPWEdit->setObjectName("NICKNAME_FindPWEdit");
        NICKNAME_FindPWEdit->setGeometry(QRect(120, 250, 190, 40));
        lb_FindPW_NICKNAME = new QLabel(page_5);
        lb_FindPW_NICKNAME->setObjectName("lb_FindPW_NICKNAME");
        lb_FindPW_NICKNAME->setGeometry(QRect(50, 310, 70, 40));
        lb_FindPW_NICKNAME->setFont(font);
        NAME_FindPWEdit = new QLineEdit(page_5);
        NAME_FindPWEdit->setObjectName("NAME_FindPWEdit");
        NAME_FindPWEdit->setGeometry(QRect(120, 310, 190, 40));
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName("page_6");
        lb_Address = new QLabel(page_6);
        lb_Address->setObjectName("lb_Address");
        lb_Address->setGeometry(QRect(5, 5, 151, 41));
        QFont font1;
        font1.setPointSize(10);
        font1.setBold(true);
        lb_Address->setFont(font1);
        lb_Address->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/Address.png);"));
        Btn_Alarm = new QPushButton(page_6);
        Btn_Alarm->setObjectName("Btn_Alarm");
        Btn_Alarm->setGeometry(QRect(265, 0, 50, 50));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/Image/Alarm.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Alarm->setIcon(icon6);
        Btn_Alarm->setIconSize(QSize(50, 50));
        Btn_Alarm->setFlat(true);
        Btn_Bascket = new QPushButton(page_6);
        Btn_Bascket->setObjectName("Btn_Bascket");
        Btn_Bascket->setGeometry(QRect(320, 0, 50, 50));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8("Image/Baskcet_2.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Bascket->setIcon(icon7);
        Btn_Bascket->setIconSize(QSize(50, 50));
        Btn_Bascket->setFlat(true);
        Search_Edit = new QLineEdit(page_6);
        Search_Edit->setObjectName("Search_Edit");
        Search_Edit->setGeometry(QRect(10, 55, 351, 40));
        Btn_Pizza = new QPushButton(page_6);
        Btn_Pizza->setObjectName("Btn_Pizza");
        Btn_Pizza->setGeometry(QRect(0, 110, 80, 80));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/Image/Pizza.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Pizza->setIcon(icon8);
        Btn_Pizza->setIconSize(QSize(75, 75));
        Btn_Pizza->setFlat(true);
        Btn_Chicken = new QPushButton(page_6);
        Btn_Chicken->setObjectName("Btn_Chicken");
        Btn_Chicken->setGeometry(QRect(95, 110, 80, 80));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/Image/Chicken.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Chicken->setIcon(icon9);
        Btn_Chicken->setIconSize(QSize(75, 75));
        Btn_Chicken->setFlat(true);
        Btn_Burger = new QPushButton(page_6);
        Btn_Burger->setObjectName("Btn_Burger");
        Btn_Burger->setGeometry(QRect(195, 110, 80, 80));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/Image/Burger.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Burger->setIcon(icon10);
        Btn_Burger->setIconSize(QSize(75, 75));
        Btn_Burger->setFlat(true);
        Btn_Meat = new QPushButton(page_6);
        Btn_Meat->setObjectName("Btn_Meat");
        Btn_Meat->setGeometry(QRect(290, 110, 80, 80));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/Image/Meat.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Meat->setIcon(icon11);
        Btn_Meat->setIconSize(QSize(75, 75));
        Btn_Meat->setFlat(true);
        Btn_Marcket1 = new QPushButton(page_6);
        Btn_Marcket1->setObjectName("Btn_Marcket1");
        Btn_Marcket1->setGeometry(QRect(0, 210, 370, 180));
        Btn_Marcket1->setFlat(false);
        Btn_Marcket2 = new QPushButton(page_6);
        Btn_Marcket2->setObjectName("Btn_Marcket2");
        Btn_Marcket2->setGeometry(QRect(0, 400, 370, 180));
        Btn_Marcket2->setFlat(false);
        Btn_Heart = new QPushButton(page_6);
        Btn_Heart->setObjectName("Btn_Heart");
        Btn_Heart->setGeometry(QRect(95, 585, 80, 80));
        Btn_Profile = new QPushButton(page_6);
        Btn_Profile->setObjectName("Btn_Profile");
        Btn_Profile->setGeometry(QRect(290, 585, 80, 80));
        Btn_Inquire = new QPushButton(page_6);
        Btn_Inquire->setObjectName("Btn_Inquire");
        Btn_Inquire->setGeometry(QRect(0, 585, 80, 80));
        Btn_List = new QPushButton(page_6);
        Btn_List->setObjectName("Btn_List");
        Btn_List->setGeometry(QRect(195, 585, 80, 80));
        lb_Photo_Marcket1 = new QLabel(page_6);
        lb_Photo_Marcket1->setObjectName("lb_Photo_Marcket1");
        lb_Photo_Marcket1->setGeometry(QRect(0, 210, 371, 121));
        lb_Photo_Marcket1->setAlignment(Qt::AlignCenter);
        lb_Photo_Marcket2 = new QLabel(page_6);
        lb_Photo_Marcket2->setObjectName("lb_Photo_Marcket2");
        lb_Photo_Marcket2->setGeometry(QRect(0, 400, 371, 121));
        lb_Photo_Marcket2->setAlignment(Qt::AlignCenter);
        lb_Marcket_Info2 = new QLabel(page_6);
        lb_Marcket_Info2->setObjectName("lb_Marcket_Info2");
        lb_Marcket_Info2->setGeometry(QRect(0, 525, 371, 51));
        lb_Marcket_Info1 = new QLabel(page_6);
        lb_Marcket_Info1->setObjectName("lb_Marcket_Info1");
        lb_Marcket_Info1->setGeometry(QRect(0, 335, 371, 51));
        label = new QLabel(page_6);
        label->setObjectName("label");
        label->setGeometry(QRect(0, 0, 371, 111));
        label->setStyleSheet(QString::fromUtf8("background-color: rgb(42, 193, 188);\n"
"border-radius:10px;\n"
""));
        stackedWidget->addWidget(page_6);
        label->raise();
        lb_Address->raise();
        Btn_Alarm->raise();
        Btn_Bascket->raise();
        Search_Edit->raise();
        Btn_Pizza->raise();
        Btn_Chicken->raise();
        Btn_Burger->raise();
        Btn_Meat->raise();
        Btn_Marcket1->raise();
        Btn_Marcket2->raise();
        Btn_Heart->raise();
        Btn_Profile->raise();
        Btn_Inquire->raise();
        Btn_List->raise();
        lb_Photo_Marcket1->raise();
        lb_Photo_Marcket2->raise();
        lb_Marcket_Info2->raise();
        lb_Marcket_Info1->raise();
        page_8 = new QWidget();
        page_8->setObjectName("page_8");
        Btn_Marcket_Back = new QPushButton(page_8);
        Btn_Marcket_Back->setObjectName("Btn_Marcket_Back");
        Btn_Marcket_Back->setGeometry(QRect(0, 0, 50, 50));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/Image/Back_2.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Marcket_Back->setIcon(icon12);
        Btn_Marcket_Back->setIconSize(QSize(50, 50));
        Btn_Marcket_Back->setFlat(true);
        lb_Image_Logo = new QLabel(page_8);
        lb_Image_Logo->setObjectName("lb_Image_Logo");
        lb_Image_Logo->setGeometry(QRect(50, 0, 110, 50));
        lb_Image_Logo->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/delivery.png);"));
        lb_Image_Logo->setAlignment(Qt::AlignCenter);
        Btn_Marcket_home = new QPushButton(page_8);
        Btn_Marcket_home->setObjectName("Btn_Marcket_home");
        Btn_Marcket_home->setGeometry(QRect(265, 0, 50, 50));
        QIcon icon13;
        icon13.addFile(QString::fromUtf8(":/Image/HOME.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Marcket_home->setIcon(icon13);
        Btn_Marcket_home->setIconSize(QSize(50, 50));
        Btn_Marcket_home->setFlat(true);
        Btn_Marcket_Bascket = new QPushButton(page_8);
        Btn_Marcket_Bascket->setObjectName("Btn_Marcket_Bascket");
        Btn_Marcket_Bascket->setGeometry(QRect(320, 0, 50, 50));
        QIcon icon14;
        icon14.addFile(QString::fromUtf8(":/Image/Baskcet.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Marcket_Bascket->setIcon(icon14);
        Btn_Marcket_Bascket->setIconSize(QSize(50, 50));
        Btn_Marcket_Bascket->setFlat(true);
        lb_Categoryname = new QLabel(page_8);
        lb_Categoryname->setObjectName("lb_Categoryname");
        lb_Categoryname->setGeometry(QRect(0, 55, 370, 40));
        Btn_Marcket_choice1 = new QPushButton(page_8);
        Btn_Marcket_choice1->setObjectName("Btn_Marcket_choice1");
        Btn_Marcket_choice1->setGeometry(QRect(0, 110, 370, 110));
        Btn_Marcket_choice1->setFlat(false);
        Btn_Marcket_choice2 = new QPushButton(page_8);
        Btn_Marcket_choice2->setObjectName("Btn_Marcket_choice2");
        Btn_Marcket_choice2->setGeometry(QRect(0, 220, 370, 110));
        Btn_Marcket_choice2->setFlat(false);
        Btn_Marcket_choice3 = new QPushButton(page_8);
        Btn_Marcket_choice3->setObjectName("Btn_Marcket_choice3");
        Btn_Marcket_choice3->setGeometry(QRect(0, 330, 370, 110));
        Btn_Marcket_choice3->setFlat(false);
        Btn_Marcket_choice4 = new QPushButton(page_8);
        Btn_Marcket_choice4->setObjectName("Btn_Marcket_choice4");
        Btn_Marcket_choice4->setGeometry(QRect(0, 440, 370, 110));
        Btn_Marcket_choice4->setFlat(false);
        Btn_Marcket_choice5 = new QPushButton(page_8);
        Btn_Marcket_choice5->setObjectName("Btn_Marcket_choice5");
        Btn_Marcket_choice5->setGeometry(QRect(0, 550, 370, 110));
        Btn_Marcket_choice5->setFlat(false);
        lb_Marcket_photo1 = new QLabel(page_8);
        lb_Marcket_photo1->setObjectName("lb_Marcket_photo1");
        lb_Marcket_photo1->setGeometry(QRect(0, 110, 95, 110));
        lb_Marcket_photo1->setAlignment(Qt::AlignCenter);
        lb_Marcket_photo2 = new QLabel(page_8);
        lb_Marcket_photo2->setObjectName("lb_Marcket_photo2");
        lb_Marcket_photo2->setGeometry(QRect(0, 220, 95, 110));
        lb_Marcket_photo2->setAlignment(Qt::AlignCenter);
        lb_Marcket_photo3 = new QLabel(page_8);
        lb_Marcket_photo3->setObjectName("lb_Marcket_photo3");
        lb_Marcket_photo3->setGeometry(QRect(0, 330, 95, 110));
        lb_Marcket_photo3->setAlignment(Qt::AlignCenter);
        lb_Marcket_photo4 = new QLabel(page_8);
        lb_Marcket_photo4->setObjectName("lb_Marcket_photo4");
        lb_Marcket_photo4->setGeometry(QRect(0, 440, 95, 110));
        lb_Marcket_photo4->setAlignment(Qt::AlignCenter);
        lb_Marcket_photo5 = new QLabel(page_8);
        lb_Marcket_photo5->setObjectName("lb_Marcket_photo5");
        lb_Marcket_photo5->setGeometry(QRect(0, 550, 95, 110));
        lb_Marcket_photo5->setAlignment(Qt::AlignCenter);
        lb_Marcket_name1 = new QLabel(page_8);
        lb_Marcket_name1->setObjectName("lb_Marcket_name1");
        lb_Marcket_name1->setGeometry(QRect(100, 110, 201, 21));
        lb_Marcket_name2 = new QLabel(page_8);
        lb_Marcket_name2->setObjectName("lb_Marcket_name2");
        lb_Marcket_name2->setGeometry(QRect(100, 220, 201, 21));
        lb_Marcket_name3 = new QLabel(page_8);
        lb_Marcket_name3->setObjectName("lb_Marcket_name3");
        lb_Marcket_name3->setGeometry(QRect(100, 330, 201, 21));
        lb_Marcket_name4 = new QLabel(page_8);
        lb_Marcket_name4->setObjectName("lb_Marcket_name4");
        lb_Marcket_name4->setGeometry(QRect(100, 440, 201, 21));
        lb_Marcket_name5 = new QLabel(page_8);
        lb_Marcket_name5->setObjectName("lb_Marcket_name5");
        lb_Marcket_name5->setGeometry(QRect(100, 550, 201, 21));
        lb_Detail4 = new QLabel(page_8);
        lb_Detail4->setObjectName("lb_Detail4");
        lb_Detail4->setGeometry(QRect(100, 480, 201, 21));
        lb_Detail3 = new QLabel(page_8);
        lb_Detail3->setObjectName("lb_Detail3");
        lb_Detail3->setGeometry(QRect(100, 370, 201, 21));
        lb_Detail5 = new QLabel(page_8);
        lb_Detail5->setObjectName("lb_Detail5");
        lb_Detail5->setGeometry(QRect(100, 590, 201, 21));
        lb_Detail2 = new QLabel(page_8);
        lb_Detail2->setObjectName("lb_Detail2");
        lb_Detail2->setGeometry(QRect(100, 260, 201, 21));
        lb_Detail1 = new QLabel(page_8);
        lb_Detail1->setObjectName("lb_Detail1");
        lb_Detail1->setGeometry(QRect(100, 150, 201, 21));
        stackedWidget->addWidget(page_8);
        page_7 = new QWidget();
        page_7->setObjectName("page_7");
        lb_Menu_name3 = new QLabel(page_7);
        lb_Menu_name3->setObjectName("lb_Menu_name3");
        lb_Menu_name3->setGeometry(QRect(5, 440, 201, 21));
        lb_Menu_Photo1 = new QLabel(page_7);
        lb_Menu_Photo1->setObjectName("lb_Menu_Photo1");
        lb_Menu_Photo1->setGeometry(QRect(270, 220, 95, 110));
        lb_Menu_Photo1->setAlignment(Qt::AlignCenter);
        lb_Menu_Photo3 = new QLabel(page_7);
        lb_Menu_Photo3->setObjectName("lb_Menu_Photo3");
        lb_Menu_Photo3->setGeometry(QRect(270, 440, 95, 110));
        lb_Menu_Photo3->setAlignment(Qt::AlignCenter);
        Btn_Menu_Bascket = new QPushButton(page_7);
        Btn_Menu_Bascket->setObjectName("Btn_Menu_Bascket");
        Btn_Menu_Bascket->setGeometry(QRect(320, 0, 50, 50));
        lb_Menu_name2 = new QLabel(page_7);
        lb_Menu_name2->setObjectName("lb_Menu_name2");
        lb_Menu_name2->setGeometry(QRect(5, 330, 201, 21));
        Btn_Menu3 = new QPushButton(page_7);
        Btn_Menu3->setObjectName("Btn_Menu3");
        Btn_Menu3->setGeometry(QRect(0, 440, 370, 110));
        Btn_Menu3->setFlat(false);
        lb_Menu_Photo4 = new QLabel(page_7);
        lb_Menu_Photo4->setObjectName("lb_Menu_Photo4");
        lb_Menu_Photo4->setGeometry(QRect(270, 550, 95, 110));
        lb_Menu_Photo4->setAlignment(Qt::AlignCenter);
        lb_Menu_Photo2 = new QLabel(page_7);
        lb_Menu_Photo2->setObjectName("lb_Menu_Photo2");
        lb_Menu_Photo2->setGeometry(QRect(270, 330, 95, 110));
        lb_Menu_Photo2->setAlignment(Qt::AlignCenter);
        lb_Menu_name4 = new QLabel(page_7);
        lb_Menu_name4->setObjectName("lb_Menu_name4");
        lb_Menu_name4->setGeometry(QRect(5, 550, 201, 21));
        Btn_Menu_home = new QPushButton(page_7);
        Btn_Menu_home->setObjectName("Btn_Menu_home");
        Btn_Menu_home->setGeometry(QRect(265, 0, 50, 50));
        Btn_Menu2 = new QPushButton(page_7);
        Btn_Menu2->setObjectName("Btn_Menu2");
        Btn_Menu2->setGeometry(QRect(0, 330, 370, 110));
        Btn_Menu2->setFlat(false);
        lb_Menu_Detail2 = new QLabel(page_7);
        lb_Menu_Detail2->setObjectName("lb_Menu_Detail2");
        lb_Menu_Detail2->setGeometry(QRect(5, 370, 201, 21));
        lb_Menu_Detail1 = new QLabel(page_7);
        lb_Menu_Detail1->setObjectName("lb_Menu_Detail1");
        lb_Menu_Detail1->setGeometry(QRect(5, 260, 201, 21));
        lb_Menu_Detail3 = new QLabel(page_7);
        lb_Menu_Detail3->setObjectName("lb_Menu_Detail3");
        lb_Menu_Detail3->setGeometry(QRect(5, 480, 201, 21));
        Btn_Menu1 = new QPushButton(page_7);
        Btn_Menu1->setObjectName("Btn_Menu1");
        Btn_Menu1->setGeometry(QRect(0, 220, 370, 110));
        Btn_Menu1->setFlat(false);
        Btn_Menu4 = new QPushButton(page_7);
        Btn_Menu4->setObjectName("Btn_Menu4");
        Btn_Menu4->setGeometry(QRect(0, 550, 370, 110));
        Btn_Menu4->setFlat(false);
        lb_Menu_name1 = new QLabel(page_7);
        lb_Menu_name1->setObjectName("lb_Menu_name1");
        lb_Menu_name1->setGeometry(QRect(5, 220, 201, 21));
        Btn_Menu_Back = new QPushButton(page_7);
        Btn_Menu_Back->setObjectName("Btn_Menu_Back");
        Btn_Menu_Back->setGeometry(QRect(0, 0, 50, 50));
        lb_Menu_Detail4 = new QLabel(page_7);
        lb_Menu_Detail4->setObjectName("lb_Menu_Detail4");
        lb_Menu_Detail4->setGeometry(QRect(5, 590, 201, 21));
        lb_Menu_Photo = new QLabel(page_7);
        lb_Menu_Photo->setObjectName("lb_Menu_Photo");
        lb_Menu_Photo->setGeometry(QRect(0, 0, 370, 120));
        lb_Menu_Photo->setAlignment(Qt::AlignCenter);
        lb_Menu_Detail = new QLabel(page_7);
        lb_Menu_Detail->setObjectName("lb_Menu_Detail");
        lb_Menu_Detail->setGeometry(QRect(0, 120, 370, 100));
        lb_Menu_Price1 = new QLabel(page_7);
        lb_Menu_Price1->setObjectName("lb_Menu_Price1");
        lb_Menu_Price1->setGeometry(QRect(5, 300, 201, 21));
        lb_Menu_Price4 = new QLabel(page_7);
        lb_Menu_Price4->setObjectName("lb_Menu_Price4");
        lb_Menu_Price4->setGeometry(QRect(5, 630, 201, 21));
        lb_Menu_Price3 = new QLabel(page_7);
        lb_Menu_Price3->setObjectName("lb_Menu_Price3");
        lb_Menu_Price3->setGeometry(QRect(5, 520, 201, 21));
        lb_Menu_Price2 = new QLabel(page_7);
        lb_Menu_Price2->setObjectName("lb_Menu_Price2");
        lb_Menu_Price2->setGeometry(QRect(5, 410, 201, 21));
        stackedWidget->addWidget(page_7);
        lb_Menu_Photo->raise();
        Btn_Menu_Bascket->raise();
        Btn_Menu3->raise();
        Btn_Menu_home->raise();
        Btn_Menu2->raise();
        lb_Menu_Detail2->raise();
        lb_Menu_Detail3->raise();
        Btn_Menu1->raise();
        Btn_Menu4->raise();
        lb_Menu_name1->raise();
        Btn_Menu_Back->raise();
        lb_Menu_Detail4->raise();
        lb_Menu_name3->raise();
        lb_Menu_Photo1->raise();
        lb_Menu_Photo3->raise();
        lb_Menu_name2->raise();
        lb_Menu_Photo4->raise();
        lb_Menu_Photo2->raise();
        lb_Menu_name4->raise();
        lb_Menu_Detail1->raise();
        lb_Menu_Detail->raise();
        lb_Menu_Price1->raise();
        lb_Menu_Price4->raise();
        lb_Menu_Price3->raise();
        lb_Menu_Price2->raise();
        page_9 = new QWidget();
        page_9->setObjectName("page_9");
        Btn_Detailmenu_Bascket = new QPushButton(page_9);
        Btn_Detailmenu_Bascket->setObjectName("Btn_Detailmenu_Bascket");
        Btn_Detailmenu_Bascket->setGeometry(QRect(325, 0, 50, 50));
        Btn_Detailmenu_Back = new QPushButton(page_9);
        Btn_Detailmenu_Back->setObjectName("Btn_Detailmenu_Back");
        Btn_Detailmenu_Back->setGeometry(QRect(5, 0, 50, 50));
        lb_Detailmenu_Photo = new QLabel(page_9);
        lb_Detailmenu_Photo->setObjectName("lb_Detailmenu_Photo");
        lb_Detailmenu_Photo->setGeometry(QRect(5, 0, 370, 120));
        lb_Detailmenu_Photo->setAlignment(Qt::AlignCenter);
        lb_Detailmenu_Detail = new QLabel(page_9);
        lb_Detailmenu_Detail->setObjectName("lb_Detailmenu_Detail");
        lb_Detailmenu_Detail->setGeometry(QRect(5, 120, 370, 100));
        Btn_Detailmenu_Home = new QPushButton(page_9);
        Btn_Detailmenu_Home->setObjectName("Btn_Detailmenu_Home");
        Btn_Detailmenu_Home->setGeometry(QRect(270, 0, 50, 50));
        Option_List = new QListWidget(page_9);
        new QListWidgetItem(Option_List);
        Option_List->setObjectName("Option_List");
        Option_List->setGeometry(QRect(0, 220, 370, 440));
        stackedWidget->addWidget(page_9);
        lb_Detailmenu_Photo->raise();
        Btn_Detailmenu_Bascket->raise();
        Btn_Detailmenu_Back->raise();
        lb_Detailmenu_Detail->raise();
        Btn_Detailmenu_Home->raise();
        Option_List->raise();
        page_10 = new QWidget();
        page_10->setObjectName("page_10");
        Btn_ConfirmMenu_Home = new QPushButton(page_10);
        Btn_ConfirmMenu_Home->setObjectName("Btn_ConfirmMenu_Home");
        Btn_ConfirmMenu_Home->setGeometry(QRect(325, 0, 50, 50));
        Btn_ConfirmMenu_Back = new QPushButton(page_10);
        Btn_ConfirmMenu_Back->setObjectName("Btn_ConfirmMenu_Back");
        Btn_ConfirmMenu_Back->setGeometry(QRect(0, 0, 50, 50));
        Btn_Delivery = new QPushButton(page_10);
        Btn_Delivery->setObjectName("Btn_Delivery");
        Btn_Delivery->setGeometry(QRect(0, 599, 370, 60));
        Btn_Delivery->setFlat(false);
        lb_Confirm_Price = new QLabel(page_10);
        lb_Confirm_Price->setObjectName("lb_Confirm_Price");
        lb_Confirm_Price->setGeometry(QRect(40, 620, 101, 16));
        Btn_Plus_Menu = new QPushButton(page_10);
        Btn_Plus_Menu->setObjectName("Btn_Plus_Menu");
        Btn_Plus_Menu->setGeometry(QRect(0, 520, 370, 60));
        Btn_Plus_Menu->setFlat(false);
        Detail_List = new QListWidget(page_10);
        Detail_List->setObjectName("Detail_List");
        Detail_List->setGeometry(QRect(0, 110, 371, 401));
        lb_Confirm_marcketname = new QLabel(page_10);
        lb_Confirm_marcketname->setObjectName("lb_Confirm_marcketname");
        lb_Confirm_marcketname->setGeometry(QRect(0, 60, 71, 41));
        lb_Confirm_time = new QLabel(page_10);
        lb_Confirm_time->setObjectName("lb_Confirm_time");
        lb_Confirm_time->setGeometry(QRect(300, 60, 71, 41));
        stackedWidget->addWidget(page_10);
        page_11 = new QWidget();
        page_11->setObjectName("page_11");
        lb_payment_name = new QLabel(page_11);
        lb_payment_name->setObjectName("lb_payment_name");
        lb_payment_name->setGeometry(QRect(0, 60, 61, 41));
        Btn_Payment_Back = new QPushButton(page_11);
        Btn_Payment_Back->setObjectName("Btn_Payment_Back");
        Btn_Payment_Back->setGeometry(QRect(0, 0, 50, 50));
        Btn_Payment = new QPushButton(page_11);
        Btn_Payment->setObjectName("Btn_Payment");
        Btn_Payment->setGeometry(QRect(0, 599, 370, 60));
        Btn_Payment->setFlat(false);
        Payment_List = new QListWidget(page_11);
        Payment_List->setObjectName("Payment_List");
        Payment_List->setGeometry(QRect(0, 110, 371, 481));
        Btn_Payment_Home = new QPushButton(page_11);
        Btn_Payment_Home->setObjectName("Btn_Payment_Home");
        Btn_Payment_Home->setGeometry(QRect(325, 0, 50, 50));
        lb_Payment_Price = new QLabel(page_11);
        lb_Payment_Price->setObjectName("lb_Payment_Price");
        lb_Payment_Price->setGeometry(QRect(40, 620, 101, 16));
        lb_payment_time = new QLabel(page_11);
        lb_payment_time->setObjectName("lb_payment_time");
        lb_payment_time->setGeometry(QRect(310, 60, 61, 41));
        stackedWidget->addWidget(page_11);
        page_12 = new QWidget();
        page_12->setObjectName("page_12");
        lb_Result_name = new QLabel(page_12);
        lb_Result_name->setObjectName("lb_Result_name");
        lb_Result_name->setGeometry(QRect(0, 60, 61, 41));
        Btn_Result_home = new QPushButton(page_12);
        Btn_Result_home->setObjectName("Btn_Result_home");
        Btn_Result_home->setGeometry(QRect(325, 0, 50, 50));
        Result_List = new QListWidget(page_12);
        Result_List->setObjectName("Result_List");
        Result_List->setGeometry(QRect(0, 110, 370, 550));
        lb_Result_time = new QLabel(page_12);
        lb_Result_time->setObjectName("lb_Result_time");
        lb_Result_time->setGeometry(QRect(310, 60, 61, 41));
        stackedWidget->addWidget(page_12);
        page_13 = new QWidget();
        page_13->setObjectName("page_13");
        Btn_Chat_Back = new QPushButton(page_13);
        Btn_Chat_Back->setObjectName("Btn_Chat_Back");
        Btn_Chat_Back->setGeometry(QRect(5, 0, 50, 50));
        Btn_Chat_Home = new QPushButton(page_13);
        Btn_Chat_Home->setObjectName("Btn_Chat_Home");
        Btn_Chat_Home->setGeometry(QRect(320, 0, 50, 50));
        Chat_TextEdit = new QTextEdit(page_13);
        Chat_TextEdit->setObjectName("Chat_TextEdit");
        Chat_TextEdit->setGeometry(QRect(0, 99, 370, 491));
        Chat_LineEdit = new QLineEdit(page_13);
        Chat_LineEdit->setObjectName("Chat_LineEdit");
        Chat_LineEdit->setGeometry(QRect(0, 610, 290, 40));
        Btn_Chat = new QPushButton(page_13);
        Btn_Chat->setObjectName("Btn_Chat");
        Btn_Chat->setGeometry(QRect(300, 610, 70, 40));
        stackedWidget->addWidget(page_13);

        retranslateUi(CustomerClient);

        stackedWidget->setCurrentIndex(5);


        QMetaObject::connectSlotsByName(CustomerClient);
    } // setupUi

    void retranslateUi(QWidget *CustomerClient)
    {
        CustomerClient->setWindowTitle(QCoreApplication::translate("CustomerClient", "CustomerClient", nullptr));
        Btn_first->setText(QString());
        lb_Logo->setText(QString());
        ID_Edit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \354\225\204\354\235\264\353\224\224 \354\236\205\353\240\245", nullptr));
        PW_Edit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \353\271\204\353\260\200\353\262\210\355\230\270 \354\236\205\353\240\245", nullptr));
        lb_ID->setText(QCoreApplication::translate("CustomerClient", "ID", nullptr));
        lb_Pw->setText(QCoreApplication::translate("CustomerClient", "PW", nullptr));
        Btn_Login->setText(QString());
        Btn_Join->setText(QString());
        Btn_FindID->setText(QString());
        Btn_FindPW->setText(QString());
        lb_JoinLogo->setText(QString());
        lb_Join_ID->setText(QCoreApplication::translate("CustomerClient", "ID", nullptr));
        lb_Join_PW->setText(QCoreApplication::translate("CustomerClient", "PW", nullptr));
        ID_JoinEdit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \354\225\204\354\235\264\353\224\224 \354\236\205\353\240\245", nullptr));
        PW_JoinEdit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \353\271\204\353\260\200\353\262\210\355\230\270 \354\236\205\353\240\245", nullptr));
        lb_Join_NAME->setText(QCoreApplication::translate("CustomerClient", "\354\235\264\353\246\204", nullptr));
        NAME_JoinEdit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \354\235\264\353\246\204 \354\236\205\353\240\245", nullptr));
        lb_Join_PHONE->setText(QCoreApplication::translate("CustomerClient", "\354\240\204\355\231\224\353\262\210\355\230\270", nullptr));
        PHONE_JoinEdit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \354\240\204\355\231\224\353\262\210\355\230\270 \354\236\205\353\240\245", nullptr));
        lb_Join_NICKNAME->setText(QCoreApplication::translate("CustomerClient", "\353\213\211\353\204\244\354\236\204", nullptr));
        NICKNAME_JoinEdit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \353\213\211\353\204\244\354\236\204 \354\236\205\353\240\245", nullptr));
        Btn_confirmID->setText(QCoreApplication::translate("CustomerClient", "\354\244\221\353\263\265\355\231\225\354\235\270", nullptr));
        Btn_confirmPHONE->setText(QCoreApplication::translate("CustomerClient", "\354\244\221\353\263\265\355\231\225\354\235\270", nullptr));
        Btn_confirmNICKNAME->setText(QCoreApplication::translate("CustomerClient", "\354\244\221\353\263\265\355\231\225\354\235\270", nullptr));
        Btn_confirmJoin->setText(QString());
        Btn_JoinBack->setText(QString());
        Btn_confirmFindID->setText(QCoreApplication::translate("CustomerClient", "ID \354\260\276\352\270\260", nullptr));
        NAME_FindIDEdit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \354\235\264\353\246\204 \354\236\205\353\240\245", nullptr));
        Btn_FindIDBack->setText(QCoreApplication::translate("CustomerClient", "\354\235\264\354\240\204", nullptr));
        NICKNAME_FindIDEdit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \353\213\211\353\204\244\354\236\204 \354\236\205\353\240\245", nullptr));
        lb_FindID_NAME->setText(QCoreApplication::translate("CustomerClient", "\354\235\264\353\246\204", nullptr));
        lb_FindIDLogo->setText(QString());
        lb_FindID_NICKNAME->setText(QCoreApplication::translate("CustomerClient", "\353\213\211\353\204\244\354\236\204", nullptr));
        lb_FindPWLogo->setText(QString());
        Btn_FindPWBack->setText(QCoreApplication::translate("CustomerClient", "\354\235\264\354\240\204", nullptr));
        lb_FindPW_NAME->setText(QCoreApplication::translate("CustomerClient", "\353\213\211\353\204\244\354\236\204", nullptr));
        ID_FindPWEdit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \354\225\204\354\235\264\353\224\224 \354\236\205\353\240\245", nullptr));
        lb_FindPW_ID->setText(QCoreApplication::translate("CustomerClient", "ID", nullptr));
        Btn_confirmFindPW->setText(QCoreApplication::translate("CustomerClient", "PW \354\260\276\352\270\260", nullptr));
        NICKNAME_FindPWEdit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \353\213\211\353\204\244\354\236\204 \354\236\205\353\240\245", nullptr));
        lb_FindPW_NICKNAME->setText(QCoreApplication::translate("CustomerClient", "\354\235\264\353\246\204", nullptr));
        NAME_FindPWEdit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \354\235\264\353\246\204 \354\236\205\353\240\245", nullptr));
        lb_Address->setText(QString());
        Btn_Alarm->setText(QString());
        Btn_Bascket->setText(QString());
        Search_Edit->setPlaceholderText(QCoreApplication::translate("CustomerClient", "  \352\262\200\354\203\211", nullptr));
        Btn_Pizza->setText(QString());
        Btn_Chicken->setText(QString());
        Btn_Burger->setText(QString());
        Btn_Meat->setText(QString());
        Btn_Marcket1->setText(QCoreApplication::translate("CustomerClient", "\354\266\224\354\262\234\352\260\200\352\262\214", nullptr));
        Btn_Marcket2->setText(QCoreApplication::translate("CustomerClient", "\354\266\224\354\262\234\352\260\200\352\262\214", nullptr));
        Btn_Heart->setText(QCoreApplication::translate("CustomerClient", "\354\260\234", nullptr));
        Btn_Profile->setText(QCoreApplication::translate("CustomerClient", "\355\224\204\353\241\234\355\225\204", nullptr));
        Btn_Inquire->setText(QCoreApplication::translate("CustomerClient", "\353\254\270\354\235\230", nullptr));
        Btn_List->setText(QCoreApplication::translate("CustomerClient", "\353\202\264\354\227\255", nullptr));
        lb_Photo_Marcket1->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Photo_Marcket2->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Marcket_Info2->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\214 \354\235\264\353\246\204 \353\260\217 \354\240\225\353\263\264", nullptr));
        lb_Marcket_Info1->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\214 \354\235\264\353\246\204 \353\260\217 \354\240\225\353\263\264", nullptr));
        label->setText(QString());
        Btn_Marcket_Back->setText(QString());
        lb_Image_Logo->setText(QString());
        Btn_Marcket_home->setText(QString());
        Btn_Marcket_Bascket->setText(QString());
        lb_Categoryname->setText(QCoreApplication::translate("CustomerClient", "\354\271\264\355\205\214\352\263\240\353\246\254 \354\235\264\353\246\204", nullptr));
        Btn_Marcket_choice1->setText(QString());
        Btn_Marcket_choice2->setText(QString());
        Btn_Marcket_choice3->setText(QString());
        Btn_Marcket_choice4->setText(QString());
        Btn_Marcket_choice5->setText(QString());
        lb_Marcket_photo1->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Marcket_photo2->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Marcket_photo3->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Marcket_photo4->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Marcket_photo5->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Marcket_name1->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        lb_Marcket_name2->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        lb_Marcket_name3->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        lb_Marcket_name4->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        lb_Marcket_name5->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        lb_Detail4->setText(QCoreApplication::translate("CustomerClient", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Detail3->setText(QCoreApplication::translate("CustomerClient", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Detail5->setText(QCoreApplication::translate("CustomerClient", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Detail2->setText(QCoreApplication::translate("CustomerClient", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Detail1->setText(QCoreApplication::translate("CustomerClient", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Menu_name3->setText(QCoreApplication::translate("CustomerClient", "\353\251\224\353\211\264 \354\235\264\353\246\204", nullptr));
        lb_Menu_Photo1->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Menu_Photo3->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        Btn_Menu_Bascket->setText(QCoreApplication::translate("CustomerClient", "\354\236\245\353\260\224\352\265\254\353\213\210", nullptr));
        lb_Menu_name2->setText(QCoreApplication::translate("CustomerClient", "\353\251\224\353\211\264 \354\235\264\353\246\204", nullptr));
        Btn_Menu3->setText(QString());
        lb_Menu_Photo4->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Menu_Photo2->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Menu_name4->setText(QCoreApplication::translate("CustomerClient", "\353\251\224\353\211\264 \354\235\264\353\246\204", nullptr));
        Btn_Menu_home->setText(QCoreApplication::translate("CustomerClient", "\355\231\210", nullptr));
        Btn_Menu2->setText(QString());
        lb_Menu_Detail2->setText(QCoreApplication::translate("CustomerClient", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Menu_Detail1->setText(QCoreApplication::translate("CustomerClient", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Menu_Detail3->setText(QCoreApplication::translate("CustomerClient", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        Btn_Menu1->setText(QString());
        Btn_Menu4->setText(QString());
        lb_Menu_name1->setText(QCoreApplication::translate("CustomerClient", "\353\251\224\353\211\264 \354\235\264\353\246\204", nullptr));
        Btn_Menu_Back->setText(QCoreApplication::translate("CustomerClient", "back", nullptr));
        lb_Menu_Detail4->setText(QCoreApplication::translate("CustomerClient", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Menu_Photo->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Menu_Detail->setText(QCoreApplication::translate("CustomerClient", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Menu_Price1->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\251", nullptr));
        lb_Menu_Price4->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\251", nullptr));
        lb_Menu_Price3->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\251", nullptr));
        lb_Menu_Price2->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\251", nullptr));
        Btn_Detailmenu_Bascket->setText(QCoreApplication::translate("CustomerClient", "\354\236\245\353\260\224\352\265\254\353\213\210", nullptr));
        Btn_Detailmenu_Back->setText(QCoreApplication::translate("CustomerClient", "back", nullptr));
        lb_Detailmenu_Photo->setText(QCoreApplication::translate("CustomerClient", "\354\202\254\354\247\204", nullptr));
        lb_Detailmenu_Detail->setText(QCoreApplication::translate("CustomerClient", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        Btn_Detailmenu_Home->setText(QCoreApplication::translate("CustomerClient", "\355\231\210", nullptr));

        const bool __sortingEnabled = Option_List->isSortingEnabled();
        Option_List->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem = Option_List->item(0);
        ___qlistwidgetitem->setText(QCoreApplication::translate("CustomerClient", "\354\230\265\354\205\230", nullptr));
        Option_List->setSortingEnabled(__sortingEnabled);

        Btn_ConfirmMenu_Home->setText(QCoreApplication::translate("CustomerClient", "\355\231\210", nullptr));
        Btn_ConfirmMenu_Back->setText(QCoreApplication::translate("CustomerClient", "back", nullptr));
        Btn_Delivery->setText(QCoreApplication::translate("CustomerClient", "\353\260\260\353\213\254 \354\243\274\353\254\270\355\225\230\352\270\260", nullptr));
        lb_Confirm_Price->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\251", nullptr));
        Btn_Plus_Menu->setText(QCoreApplication::translate("CustomerClient", "+ \353\215\224 \353\213\264\354\234\274\353\237\254 \352\260\200\352\270\260", nullptr));
        lb_Confirm_marcketname->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\214 \354\235\264\353\246\204 ", nullptr));
        lb_Confirm_time->setText(QCoreApplication::translate("CustomerClient", "\353\217\204\354\260\251 \354\213\234\352\260\204", nullptr));
        lb_payment_name->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        Btn_Payment_Back->setText(QCoreApplication::translate("CustomerClient", "back", nullptr));
        Btn_Payment->setText(QCoreApplication::translate("CustomerClient", "\352\262\260\354\240\234\355\225\230\352\270\260", nullptr));
        Btn_Payment_Home->setText(QCoreApplication::translate("CustomerClient", "\355\231\210", nullptr));
        lb_Payment_Price->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\251", nullptr));
        lb_payment_time->setText(QCoreApplication::translate("CustomerClient", "\353\217\204\354\260\251 \354\213\234\352\260\204", nullptr));
        lb_Result_name->setText(QCoreApplication::translate("CustomerClient", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        Btn_Result_home->setText(QCoreApplication::translate("CustomerClient", "\355\231\210", nullptr));
        lb_Result_time->setText(QCoreApplication::translate("CustomerClient", "\353\217\204\354\260\251 \354\213\234\352\260\204", nullptr));
        Btn_Chat_Back->setText(QCoreApplication::translate("CustomerClient", "back", nullptr));
        Btn_Chat_Home->setText(QCoreApplication::translate("CustomerClient", "\355\231\210", nullptr));
        Btn_Chat->setText(QCoreApplication::translate("CustomerClient", "\354\236\205\353\240\245", nullptr));
    } // retranslateUi

};

namespace Ui {
    class CustomerClient: public Ui_CustomerClient {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CUSTOMERCLIENT_H
