/********************************************************************************
** Form generated from reading UI file 'orderpage.ui'
**
** Created by: Qt User Interface Compiler version 6.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ORDERPAGE_H
#define UI_ORDERPAGE_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_OrderPage
{
public:
    QStackedWidget *stackedWidget;
    QWidget *page;
    QPushButton *Btn_Burger;
    QPushButton *Btn_Profile;
    QPushButton *Btn_Heart;
    QLineEdit *Search_Edit;
    QPushButton *Btn_Alarm;
    QPushButton *Btn_Marcket2;
    QPushButton *Btn_List;
    QLabel *lb_Address;
    QPushButton *Btn_Search;
    QPushButton *Btn_Inquire;
    QPushButton *Btn_Pizza;
    QLabel *label;
    QPushButton *Btn_Chicken;
    QPushButton *Btn_Meat;
    QPushButton *Btn_Marcket1;
    QPushButton *Btn_Bascket;
    QWidget *page_5;
    QWidget *page_2;
    QLabel *lb_Detail5;
    QLabel *lb_Marcket_name4;
    QLabel *lb_Detail4;
    QLabel *lb_Marcket_photo5;
    QLabel *lb_Marcket_name3;
    QLabel *lb_Marcket_name5;
    QPushButton *Btn_Marcket_Bascket;
    QLabel *lb_Categoryname;
    QPushButton *Btn_Marcket_choice4;
    QLabel *lb_Marcket_photo4;
    QLabel *lb_Detail3;
    QPushButton *Btn_Marcket_choice3;
    QLabel *lb_Detail1;
    QLabel *lb_Detail2;
    QLabel *lb_Marcket_photo2;
    QLabel *lb_Image_Logo;
    QLabel *lb_Marcket_name2;
    QPushButton *Btn_Marcket_Back;
    QPushButton *Btn_Marcket_choice2;
    QPushButton *Btn_Marcket_choice1;
    QPushButton *Btn_Marcket_home;
    QLabel *lb_Marcket_photo1;
    QLabel *lb_Marcket_photo3;
    QLabel *lb_Marcket_name1;
    QPushButton *Btn_Marcket_choice5;
    QWidget *page_3;
    QLabel *lb_Menu_name3;
    QLabel *lb_Menu_Detail;
    QPushButton *Btn_Menu2;
    QLabel *lb_Menu_Detail4;
    QPushButton *Btn_Menu_Back;
    QLabel *lb_Menu_name2;
    QPushButton *Btn_Menu3;
    QLabel *lb_Menu_Detail3;
    QLabel *lb_Menu_Photo1;
    QLabel *lb_Menu_Price1;
    QLabel *lb_Menu_Price2;
    QLabel *lb_Menu_name4;
    QLabel *lb_Menu_Photo2;
    QLabel *lb_Menu_Detail2;
    QLabel *lb_Menu_Price3;
    QLabel *lb_Menu_Photo;
    QPushButton *Btn_Menu4;
    QPushButton *Btn_Menu_Bascket;
    QLabel *lb_Menu_name1;
    QPushButton *Btn_Menu1;
    QLabel *lb_Menu_Photo4;
    QPushButton *Btn_Menu_home;
    QLabel *lb_Menu_Detail1;
    QLabel *lb_Menu_Price4;
    QLabel *lb_Menu_Photo3;
    QWidget *page_4;
    QPushButton *Btn_Detailmenu_Bascket;
    QPushButton *Btn_Detailmenu_Back;
    QListWidget *Option_List;
    QLabel *lb_Detailmenu_Detail;
    QPushButton *Btn_Detailmenu_Home;
    QLabel *lb_Detailmenu_Photo;

    void setupUi(QWidget *OrderPage)
    {
        if (OrderPage->objectName().isEmpty())
            OrderPage->setObjectName("OrderPage");
        OrderPage->resize(372, 668);
        OrderPage->setMinimumSize(QSize(372, 668));
        OrderPage->setMaximumSize(QSize(372, 668));
        stackedWidget = new QStackedWidget(OrderPage);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(0, 0, 375, 665));
        page = new QWidget();
        page->setObjectName("page");
        Btn_Burger = new QPushButton(page);
        Btn_Burger->setObjectName("Btn_Burger");
        Btn_Burger->setGeometry(QRect(195, 120, 80, 80));
        Btn_Burger->setCursor(QCursor(Qt::PointingHandCursor));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Image/Burger.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Burger->setIcon(icon);
        Btn_Burger->setIconSize(QSize(75, 75));
        Btn_Burger->setFlat(true);
        Btn_Profile = new QPushButton(page);
        Btn_Profile->setObjectName("Btn_Profile");
        Btn_Profile->setGeometry(QRect(285, 590, 70, 70));
        Btn_Profile->setCursor(QCursor(Qt::PointingHandCursor));
        Btn_Profile->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/profile.png);"));
        Btn_Profile->setFlat(true);
        Btn_Heart = new QPushButton(page);
        Btn_Heart->setObjectName("Btn_Heart");
        Btn_Heart->setGeometry(QRect(105, 590, 70, 70));
        Btn_Heart->setCursor(QCursor(Qt::PointingHandCursor));
        Btn_Heart->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/heart.png);"));
        Btn_Heart->setFlat(true);
        Search_Edit = new QLineEdit(page);
        Search_Edit->setObjectName("Search_Edit");
        Search_Edit->setGeometry(QRect(10, 55, 310, 40));
        Search_Edit->setStyleSheet(QString::fromUtf8("border-radius:10px;"));
        Btn_Alarm = new QPushButton(page);
        Btn_Alarm->setObjectName("Btn_Alarm");
        Btn_Alarm->setGeometry(QRect(265, 0, 50, 50));
        Btn_Alarm->setCursor(QCursor(Qt::PointingHandCursor));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Image/Alarm.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Alarm->setIcon(icon1);
        Btn_Alarm->setIconSize(QSize(50, 50));
        Btn_Alarm->setFlat(true);
        Btn_Marcket2 = new QPushButton(page);
        Btn_Marcket2->setObjectName("Btn_Marcket2");
        Btn_Marcket2->setGeometry(QRect(0, 400, 370, 180));
        Btn_Marcket2->setCursor(QCursor(Qt::PointingHandCursor));
        Btn_Marcket2->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/Screenshot_20240216_114425.jpg);\n"
"border-radius:10px;"));
        Btn_Marcket2->setFlat(true);
        Btn_List = new QPushButton(page);
        Btn_List->setObjectName("Btn_List");
        Btn_List->setGeometry(QRect(195, 590, 70, 70));
        Btn_List->setCursor(QCursor(Qt::PointingHandCursor));
        Btn_List->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/order.png);"));
        Btn_List->setFlat(true);
        lb_Address = new QLabel(page);
        lb_Address->setObjectName("lb_Address");
        lb_Address->setGeometry(QRect(5, 5, 151, 41));
        QFont font;
        font.setPointSize(10);
        font.setBold(true);
        lb_Address->setFont(font);
        lb_Address->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/Address.png);"));
        Btn_Search = new QPushButton(page);
        Btn_Search->setObjectName("Btn_Search");
        Btn_Search->setGeometry(QRect(330, 60, 30, 30));
        Btn_Search->setCursor(QCursor(Qt::PointingHandCursor));
        Btn_Search->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/search.png);"));
        Btn_Search->setFlat(true);
        Btn_Inquire = new QPushButton(page);
        Btn_Inquire->setObjectName("Btn_Inquire");
        Btn_Inquire->setGeometry(QRect(15, 590, 70, 70));
        Btn_Inquire->setCursor(QCursor(Qt::PointingHandCursor));
        Btn_Inquire->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/center.PNG);"));
        Btn_Inquire->setFlat(true);
        Btn_Pizza = new QPushButton(page);
        Btn_Pizza->setObjectName("Btn_Pizza");
        Btn_Pizza->setGeometry(QRect(0, 120, 80, 80));
        Btn_Pizza->setCursor(QCursor(Qt::PointingHandCursor));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Image/Pizza.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Pizza->setIcon(icon2);
        Btn_Pizza->setIconSize(QSize(75, 75));
        Btn_Pizza->setFlat(true);
        label = new QLabel(page);
        label->setObjectName("label");
        label->setGeometry(QRect(0, 0, 370, 110));
        label->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
""));
        Btn_Chicken = new QPushButton(page);
        Btn_Chicken->setObjectName("Btn_Chicken");
        Btn_Chicken->setGeometry(QRect(95, 120, 80, 80));
        Btn_Chicken->setCursor(QCursor(Qt::PointingHandCursor));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/Image/Chicken.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Chicken->setIcon(icon3);
        Btn_Chicken->setIconSize(QSize(75, 75));
        Btn_Chicken->setFlat(true);
        Btn_Meat = new QPushButton(page);
        Btn_Meat->setObjectName("Btn_Meat");
        Btn_Meat->setGeometry(QRect(290, 120, 80, 80));
        Btn_Meat->setCursor(QCursor(Qt::PointingHandCursor));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/Image/Meat.png"), QSize(), QIcon::Normal, QIcon::Off);
        Btn_Meat->setIcon(icon4);
        Btn_Meat->setIconSize(QSize(75, 75));
        Btn_Meat->setFlat(true);
        Btn_Marcket1 = new QPushButton(page);
        Btn_Marcket1->setObjectName("Btn_Marcket1");
        Btn_Marcket1->setGeometry(QRect(0, 210, 370, 180));
        Btn_Marcket1->setCursor(QCursor(Qt::PointingHandCursor));
        Btn_Marcket1->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/Screenshot_20240216_114855.jpg);\n"
"border-radius:10px;"));
        Btn_Marcket1->setFlat(true);
        Btn_Bascket = new QPushButton(page);
        Btn_Bascket->setObjectName("Btn_Bascket");
        Btn_Bascket->setGeometry(QRect(315, 0, 50, 50));
        Btn_Bascket->setCursor(QCursor(Qt::PointingHandCursor));
        Btn_Bascket->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/Baskcet_2.png);"));
        Btn_Bascket->setIconSize(QSize(50, 50));
        Btn_Bascket->setFlat(true);
        stackedWidget->addWidget(page);
        label->raise();
        Btn_Marcket1->raise();
        Btn_Burger->raise();
        Search_Edit->raise();
        lb_Address->raise();
        Btn_Pizza->raise();
        Btn_Chicken->raise();
        Btn_Meat->raise();
        Btn_Marcket2->raise();
        Btn_Bascket->raise();
        Btn_Alarm->raise();
        Btn_Search->raise();
        Btn_Inquire->raise();
        Btn_Profile->raise();
        Btn_List->raise();
        Btn_Heart->raise();
        page_5 = new QWidget();
        page_5->setObjectName("page_5");
        stackedWidget->addWidget(page_5);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        lb_Detail5 = new QLabel(page_2);
        lb_Detail5->setObjectName("lb_Detail5");
        lb_Detail5->setGeometry(QRect(100, 590, 201, 21));
        lb_Marcket_name4 = new QLabel(page_2);
        lb_Marcket_name4->setObjectName("lb_Marcket_name4");
        lb_Marcket_name4->setGeometry(QRect(100, 440, 201, 21));
        lb_Detail4 = new QLabel(page_2);
        lb_Detail4->setObjectName("lb_Detail4");
        lb_Detail4->setGeometry(QRect(100, 480, 201, 21));
        lb_Marcket_photo5 = new QLabel(page_2);
        lb_Marcket_photo5->setObjectName("lb_Marcket_photo5");
        lb_Marcket_photo5->setGeometry(QRect(0, 550, 95, 110));
        lb_Marcket_photo5->setAlignment(Qt::AlignCenter);
        lb_Marcket_name3 = new QLabel(page_2);
        lb_Marcket_name3->setObjectName("lb_Marcket_name3");
        lb_Marcket_name3->setGeometry(QRect(100, 330, 201, 21));
        lb_Marcket_name5 = new QLabel(page_2);
        lb_Marcket_name5->setObjectName("lb_Marcket_name5");
        lb_Marcket_name5->setGeometry(QRect(100, 550, 201, 21));
        Btn_Marcket_Bascket = new QPushButton(page_2);
        Btn_Marcket_Bascket->setObjectName("Btn_Marcket_Bascket");
        Btn_Marcket_Bascket->setGeometry(QRect(320, 0, 50, 50));
        Btn_Marcket_Bascket->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/Baskcet.png);"));
        Btn_Marcket_Bascket->setIconSize(QSize(50, 50));
        Btn_Marcket_Bascket->setFlat(true);
        lb_Categoryname = new QLabel(page_2);
        lb_Categoryname->setObjectName("lb_Categoryname");
        lb_Categoryname->setGeometry(QRect(0, 55, 370, 40));
        Btn_Marcket_choice4 = new QPushButton(page_2);
        Btn_Marcket_choice4->setObjectName("Btn_Marcket_choice4");
        Btn_Marcket_choice4->setGeometry(QRect(0, 440, 370, 110));
        Btn_Marcket_choice4->setFlat(false);
        lb_Marcket_photo4 = new QLabel(page_2);
        lb_Marcket_photo4->setObjectName("lb_Marcket_photo4");
        lb_Marcket_photo4->setGeometry(QRect(0, 440, 95, 110));
        lb_Marcket_photo4->setAlignment(Qt::AlignCenter);
        lb_Detail3 = new QLabel(page_2);
        lb_Detail3->setObjectName("lb_Detail3");
        lb_Detail3->setGeometry(QRect(100, 370, 201, 21));
        Btn_Marcket_choice3 = new QPushButton(page_2);
        Btn_Marcket_choice3->setObjectName("Btn_Marcket_choice3");
        Btn_Marcket_choice3->setGeometry(QRect(0, 330, 370, 110));
        Btn_Marcket_choice3->setFlat(false);
        lb_Detail1 = new QLabel(page_2);
        lb_Detail1->setObjectName("lb_Detail1");
        lb_Detail1->setGeometry(QRect(100, 150, 201, 21));
        lb_Detail2 = new QLabel(page_2);
        lb_Detail2->setObjectName("lb_Detail2");
        lb_Detail2->setGeometry(QRect(100, 260, 201, 21));
        lb_Marcket_photo2 = new QLabel(page_2);
        lb_Marcket_photo2->setObjectName("lb_Marcket_photo2");
        lb_Marcket_photo2->setGeometry(QRect(0, 220, 95, 110));
        lb_Marcket_photo2->setAlignment(Qt::AlignCenter);
        lb_Image_Logo = new QLabel(page_2);
        lb_Image_Logo->setObjectName("lb_Image_Logo");
        lb_Image_Logo->setGeometry(QRect(50, 0, 110, 50));
        lb_Image_Logo->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/delivery.png);"));
        lb_Image_Logo->setAlignment(Qt::AlignCenter);
        lb_Marcket_name2 = new QLabel(page_2);
        lb_Marcket_name2->setObjectName("lb_Marcket_name2");
        lb_Marcket_name2->setGeometry(QRect(100, 220, 201, 21));
        Btn_Marcket_Back = new QPushButton(page_2);
        Btn_Marcket_Back->setObjectName("Btn_Marcket_Back");
        Btn_Marcket_Back->setGeometry(QRect(0, 0, 50, 50));
        Btn_Marcket_Back->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/Back_2.png);"));
        Btn_Marcket_Back->setIconSize(QSize(50, 50));
        Btn_Marcket_Back->setFlat(true);
        Btn_Marcket_choice2 = new QPushButton(page_2);
        Btn_Marcket_choice2->setObjectName("Btn_Marcket_choice2");
        Btn_Marcket_choice2->setGeometry(QRect(0, 220, 370, 110));
        Btn_Marcket_choice2->setFlat(false);
        Btn_Marcket_choice1 = new QPushButton(page_2);
        Btn_Marcket_choice1->setObjectName("Btn_Marcket_choice1");
        Btn_Marcket_choice1->setGeometry(QRect(0, 110, 370, 110));
        Btn_Marcket_choice1->setFlat(false);
        Btn_Marcket_home = new QPushButton(page_2);
        Btn_Marcket_home->setObjectName("Btn_Marcket_home");
        Btn_Marcket_home->setGeometry(QRect(265, 0, 50, 50));
        Btn_Marcket_home->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/HOME.png);"));
        Btn_Marcket_home->setIconSize(QSize(50, 50));
        Btn_Marcket_home->setFlat(true);
        lb_Marcket_photo1 = new QLabel(page_2);
        lb_Marcket_photo1->setObjectName("lb_Marcket_photo1");
        lb_Marcket_photo1->setGeometry(QRect(0, 110, 95, 110));
        lb_Marcket_photo1->setAlignment(Qt::AlignCenter);
        lb_Marcket_photo3 = new QLabel(page_2);
        lb_Marcket_photo3->setObjectName("lb_Marcket_photo3");
        lb_Marcket_photo3->setGeometry(QRect(0, 330, 95, 110));
        lb_Marcket_photo3->setAlignment(Qt::AlignCenter);
        lb_Marcket_name1 = new QLabel(page_2);
        lb_Marcket_name1->setObjectName("lb_Marcket_name1");
        lb_Marcket_name1->setGeometry(QRect(100, 110, 201, 21));
        Btn_Marcket_choice5 = new QPushButton(page_2);
        Btn_Marcket_choice5->setObjectName("Btn_Marcket_choice5");
        Btn_Marcket_choice5->setGeometry(QRect(0, 550, 370, 110));
        Btn_Marcket_choice5->setFlat(false);
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        lb_Menu_name3 = new QLabel(page_3);
        lb_Menu_name3->setObjectName("lb_Menu_name3");
        lb_Menu_name3->setGeometry(QRect(5, 440, 201, 21));
        lb_Menu_Detail = new QLabel(page_3);
        lb_Menu_Detail->setObjectName("lb_Menu_Detail");
        lb_Menu_Detail->setGeometry(QRect(0, 120, 370, 100));
        Btn_Menu2 = new QPushButton(page_3);
        Btn_Menu2->setObjectName("Btn_Menu2");
        Btn_Menu2->setGeometry(QRect(0, 330, 370, 110));
        Btn_Menu2->setFlat(false);
        lb_Menu_Detail4 = new QLabel(page_3);
        lb_Menu_Detail4->setObjectName("lb_Menu_Detail4");
        lb_Menu_Detail4->setGeometry(QRect(5, 590, 201, 21));
        Btn_Menu_Back = new QPushButton(page_3);
        Btn_Menu_Back->setObjectName("Btn_Menu_Back");
        Btn_Menu_Back->setGeometry(QRect(0, 0, 50, 50));
        Btn_Menu_Back->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/Back_2.png);"));
        Btn_Menu_Back->setFlat(true);
        lb_Menu_name2 = new QLabel(page_3);
        lb_Menu_name2->setObjectName("lb_Menu_name2");
        lb_Menu_name2->setGeometry(QRect(5, 330, 201, 21));
        Btn_Menu3 = new QPushButton(page_3);
        Btn_Menu3->setObjectName("Btn_Menu3");
        Btn_Menu3->setGeometry(QRect(0, 440, 370, 110));
        Btn_Menu3->setFlat(false);
        lb_Menu_Detail3 = new QLabel(page_3);
        lb_Menu_Detail3->setObjectName("lb_Menu_Detail3");
        lb_Menu_Detail3->setGeometry(QRect(5, 480, 201, 21));
        lb_Menu_Photo1 = new QLabel(page_3);
        lb_Menu_Photo1->setObjectName("lb_Menu_Photo1");
        lb_Menu_Photo1->setGeometry(QRect(270, 220, 95, 110));
        lb_Menu_Photo1->setAlignment(Qt::AlignCenter);
        lb_Menu_Price1 = new QLabel(page_3);
        lb_Menu_Price1->setObjectName("lb_Menu_Price1");
        lb_Menu_Price1->setGeometry(QRect(5, 300, 201, 21));
        lb_Menu_Price2 = new QLabel(page_3);
        lb_Menu_Price2->setObjectName("lb_Menu_Price2");
        lb_Menu_Price2->setGeometry(QRect(5, 410, 201, 21));
        lb_Menu_name4 = new QLabel(page_3);
        lb_Menu_name4->setObjectName("lb_Menu_name4");
        lb_Menu_name4->setGeometry(QRect(5, 550, 201, 21));
        lb_Menu_Photo2 = new QLabel(page_3);
        lb_Menu_Photo2->setObjectName("lb_Menu_Photo2");
        lb_Menu_Photo2->setGeometry(QRect(270, 330, 95, 110));
        lb_Menu_Photo2->setAlignment(Qt::AlignCenter);
        lb_Menu_Detail2 = new QLabel(page_3);
        lb_Menu_Detail2->setObjectName("lb_Menu_Detail2");
        lb_Menu_Detail2->setGeometry(QRect(5, 370, 201, 21));
        lb_Menu_Price3 = new QLabel(page_3);
        lb_Menu_Price3->setObjectName("lb_Menu_Price3");
        lb_Menu_Price3->setGeometry(QRect(5, 520, 201, 21));
        lb_Menu_Photo = new QLabel(page_3);
        lb_Menu_Photo->setObjectName("lb_Menu_Photo");
        lb_Menu_Photo->setGeometry(QRect(0, 0, 370, 120));
        lb_Menu_Photo->setAlignment(Qt::AlignCenter);
        Btn_Menu4 = new QPushButton(page_3);
        Btn_Menu4->setObjectName("Btn_Menu4");
        Btn_Menu4->setGeometry(QRect(0, 550, 370, 110));
        Btn_Menu4->setFlat(false);
        Btn_Menu_Bascket = new QPushButton(page_3);
        Btn_Menu_Bascket->setObjectName("Btn_Menu_Bascket");
        Btn_Menu_Bascket->setGeometry(QRect(320, 0, 50, 50));
        Btn_Menu_Bascket->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/Baskcet.png);"));
        lb_Menu_name1 = new QLabel(page_3);
        lb_Menu_name1->setObjectName("lb_Menu_name1");
        lb_Menu_name1->setGeometry(QRect(5, 220, 201, 21));
        Btn_Menu1 = new QPushButton(page_3);
        Btn_Menu1->setObjectName("Btn_Menu1");
        Btn_Menu1->setGeometry(QRect(0, 220, 370, 110));
        Btn_Menu1->setFlat(false);
        lb_Menu_Photo4 = new QLabel(page_3);
        lb_Menu_Photo4->setObjectName("lb_Menu_Photo4");
        lb_Menu_Photo4->setGeometry(QRect(270, 550, 95, 110));
        lb_Menu_Photo4->setAlignment(Qt::AlignCenter);
        Btn_Menu_home = new QPushButton(page_3);
        Btn_Menu_home->setObjectName("Btn_Menu_home");
        Btn_Menu_home->setGeometry(QRect(265, 0, 50, 50));
        Btn_Menu_home->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/HOME.png);"));
        lb_Menu_Detail1 = new QLabel(page_3);
        lb_Menu_Detail1->setObjectName("lb_Menu_Detail1");
        lb_Menu_Detail1->setGeometry(QRect(5, 260, 201, 21));
        lb_Menu_Price4 = new QLabel(page_3);
        lb_Menu_Price4->setObjectName("lb_Menu_Price4");
        lb_Menu_Price4->setGeometry(QRect(5, 630, 201, 21));
        lb_Menu_Photo3 = new QLabel(page_3);
        lb_Menu_Photo3->setObjectName("lb_Menu_Photo3");
        lb_Menu_Photo3->setGeometry(QRect(270, 440, 95, 110));
        lb_Menu_Photo3->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_3);
        lb_Menu_Photo->raise();
        lb_Menu_name3->raise();
        lb_Menu_Detail->raise();
        Btn_Menu2->raise();
        lb_Menu_Detail4->raise();
        Btn_Menu_Back->raise();
        lb_Menu_name2->raise();
        Btn_Menu3->raise();
        lb_Menu_Detail3->raise();
        lb_Menu_Photo1->raise();
        lb_Menu_Price1->raise();
        lb_Menu_Price2->raise();
        lb_Menu_name4->raise();
        lb_Menu_Photo2->raise();
        lb_Menu_Detail2->raise();
        lb_Menu_Price3->raise();
        Btn_Menu4->raise();
        Btn_Menu_Bascket->raise();
        lb_Menu_name1->raise();
        Btn_Menu1->raise();
        lb_Menu_Photo4->raise();
        Btn_Menu_home->raise();
        lb_Menu_Detail1->raise();
        lb_Menu_Price4->raise();
        lb_Menu_Photo3->raise();
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        Btn_Detailmenu_Bascket = new QPushButton(page_4);
        Btn_Detailmenu_Bascket->setObjectName("Btn_Detailmenu_Bascket");
        Btn_Detailmenu_Bascket->setGeometry(QRect(320, 0, 50, 50));
        Btn_Detailmenu_Bascket->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/Baskcet.png);"));
        Btn_Detailmenu_Bascket->setFlat(true);
        Btn_Detailmenu_Back = new QPushButton(page_4);
        Btn_Detailmenu_Back->setObjectName("Btn_Detailmenu_Back");
        Btn_Detailmenu_Back->setGeometry(QRect(0, 0, 50, 50));
        Btn_Detailmenu_Back->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/Back_2.png);"));
        Btn_Detailmenu_Back->setFlat(true);
        Option_List = new QListWidget(page_4);
        new QListWidgetItem(Option_List);
        Option_List->setObjectName("Option_List");
        Option_List->setGeometry(QRect(0, 220, 370, 440));
        lb_Detailmenu_Detail = new QLabel(page_4);
        lb_Detailmenu_Detail->setObjectName("lb_Detailmenu_Detail");
        lb_Detailmenu_Detail->setGeometry(QRect(0, 120, 370, 100));
        Btn_Detailmenu_Home = new QPushButton(page_4);
        Btn_Detailmenu_Home->setObjectName("Btn_Detailmenu_Home");
        Btn_Detailmenu_Home->setGeometry(QRect(265, 0, 50, 50));
        Btn_Detailmenu_Home->setStyleSheet(QString::fromUtf8("border-image: url(:/Image/HOME.png);"));
        Btn_Detailmenu_Home->setFlat(true);
        lb_Detailmenu_Photo = new QLabel(page_4);
        lb_Detailmenu_Photo->setObjectName("lb_Detailmenu_Photo");
        lb_Detailmenu_Photo->setGeometry(QRect(0, 0, 370, 120));
        lb_Detailmenu_Photo->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_4);
        lb_Detailmenu_Photo->raise();
        Btn_Detailmenu_Bascket->raise();
        Btn_Detailmenu_Back->raise();
        Option_List->raise();
        lb_Detailmenu_Detail->raise();
        Btn_Detailmenu_Home->raise();

        retranslateUi(OrderPage);
        QObject::connect(Search_Edit, &QLineEdit::returnPressed, Btn_Search, qOverload<>(&QPushButton::click));

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(OrderPage);
    } // setupUi

    void retranslateUi(QWidget *OrderPage)
    {
        OrderPage->setWindowTitle(QCoreApplication::translate("OrderPage", "Form", nullptr));
        Btn_Burger->setText(QString());
        Btn_Profile->setText(QString());
        Btn_Heart->setText(QString());
        Search_Edit->setPlaceholderText(QCoreApplication::translate("OrderPage", "  \352\262\200\354\203\211", nullptr));
        Btn_Alarm->setText(QString());
        Btn_Marcket2->setText(QString());
        Btn_List->setText(QString());
        lb_Address->setText(QString());
        Btn_Search->setText(QString());
        Btn_Inquire->setText(QString());
        Btn_Pizza->setText(QString());
        label->setText(QString());
        Btn_Chicken->setText(QString());
        Btn_Meat->setText(QString());
        Btn_Marcket1->setText(QString());
        Btn_Bascket->setText(QString());
        lb_Detail5->setText(QCoreApplication::translate("OrderPage", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Marcket_name4->setText(QCoreApplication::translate("OrderPage", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        lb_Detail4->setText(QCoreApplication::translate("OrderPage", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Marcket_photo5->setText(QCoreApplication::translate("OrderPage", "\354\202\254\354\247\204", nullptr));
        lb_Marcket_name3->setText(QCoreApplication::translate("OrderPage", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        lb_Marcket_name5->setText(QCoreApplication::translate("OrderPage", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        Btn_Marcket_Bascket->setText(QString());
        lb_Categoryname->setText(QCoreApplication::translate("OrderPage", "\354\271\264\355\205\214\352\263\240\353\246\254 \354\235\264\353\246\204", nullptr));
        Btn_Marcket_choice4->setText(QString());
        lb_Marcket_photo4->setText(QCoreApplication::translate("OrderPage", "\354\202\254\354\247\204", nullptr));
        lb_Detail3->setText(QCoreApplication::translate("OrderPage", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        Btn_Marcket_choice3->setText(QString());
        lb_Detail1->setText(QCoreApplication::translate("OrderPage", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Detail2->setText(QCoreApplication::translate("OrderPage", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Marcket_photo2->setText(QCoreApplication::translate("OrderPage", "\354\202\254\354\247\204", nullptr));
        lb_Image_Logo->setText(QString());
        lb_Marcket_name2->setText(QCoreApplication::translate("OrderPage", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        Btn_Marcket_Back->setText(QString());
        Btn_Marcket_choice2->setText(QString());
        Btn_Marcket_choice1->setText(QString());
        Btn_Marcket_home->setText(QString());
        lb_Marcket_photo1->setText(QCoreApplication::translate("OrderPage", "\354\202\254\354\247\204", nullptr));
        lb_Marcket_photo3->setText(QCoreApplication::translate("OrderPage", "\354\202\254\354\247\204", nullptr));
        lb_Marcket_name1->setText(QCoreApplication::translate("OrderPage", "\352\260\200\352\262\214 \354\235\264\353\246\204", nullptr));
        Btn_Marcket_choice5->setText(QString());
        lb_Menu_name3->setText(QCoreApplication::translate("OrderPage", "\353\251\224\353\211\264 \354\235\264\353\246\204", nullptr));
        lb_Menu_Detail->setText(QCoreApplication::translate("OrderPage", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        Btn_Menu2->setText(QString());
        lb_Menu_Detail4->setText(QCoreApplication::translate("OrderPage", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        Btn_Menu_Back->setText(QString());
        lb_Menu_name2->setText(QCoreApplication::translate("OrderPage", "\353\251\224\353\211\264 \354\235\264\353\246\204", nullptr));
        Btn_Menu3->setText(QString());
        lb_Menu_Detail3->setText(QCoreApplication::translate("OrderPage", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Menu_Photo1->setText(QCoreApplication::translate("OrderPage", "\354\202\254\354\247\204", nullptr));
        lb_Menu_Price1->setText(QCoreApplication::translate("OrderPage", "\352\260\200\352\262\251", nullptr));
        lb_Menu_Price2->setText(QCoreApplication::translate("OrderPage", "\352\260\200\352\262\251", nullptr));
        lb_Menu_name4->setText(QCoreApplication::translate("OrderPage", "\353\251\224\353\211\264 \354\235\264\353\246\204", nullptr));
        lb_Menu_Photo2->setText(QCoreApplication::translate("OrderPage", "\354\202\254\354\247\204", nullptr));
        lb_Menu_Detail2->setText(QCoreApplication::translate("OrderPage", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Menu_Price3->setText(QCoreApplication::translate("OrderPage", "\352\260\200\352\262\251", nullptr));
        lb_Menu_Photo->setText(QCoreApplication::translate("OrderPage", "\354\202\254\354\247\204", nullptr));
        Btn_Menu4->setText(QString());
        Btn_Menu_Bascket->setText(QString());
        lb_Menu_name1->setText(QCoreApplication::translate("OrderPage", "\353\251\224\353\211\264 \354\235\264\353\246\204", nullptr));
        Btn_Menu1->setText(QString());
        lb_Menu_Photo4->setText(QCoreApplication::translate("OrderPage", "\354\202\254\354\247\204", nullptr));
        Btn_Menu_home->setText(QString());
        lb_Menu_Detail1->setText(QCoreApplication::translate("OrderPage", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        lb_Menu_Price4->setText(QCoreApplication::translate("OrderPage", "\352\260\200\352\262\251", nullptr));
        lb_Menu_Photo3->setText(QCoreApplication::translate("OrderPage", "\354\202\254\354\247\204", nullptr));
        Btn_Detailmenu_Bascket->setText(QString());
        Btn_Detailmenu_Back->setText(QString());

        const bool __sortingEnabled = Option_List->isSortingEnabled();
        Option_List->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem = Option_List->item(0);
        ___qlistwidgetitem->setText(QCoreApplication::translate("OrderPage", "\354\230\265\354\205\230", nullptr));
        Option_List->setSortingEnabled(__sortingEnabled);

        lb_Detailmenu_Detail->setText(QCoreApplication::translate("OrderPage", "\354\204\270\353\266\200 \354\240\225\353\263\264", nullptr));
        Btn_Detailmenu_Home->setText(QString());
        lb_Detailmenu_Photo->setText(QCoreApplication::translate("OrderPage", "\354\202\254\354\247\204", nullptr));
    } // retranslateUi

};

namespace Ui {
    class OrderPage: public Ui_OrderPage {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ORDERPAGE_H
